#!/bin/zsh
# https://github.com/mihirlad55/dwm/blob/patched/startdwm
# test

logfile=/home/paulw/.dwm.log

dwmlog() {
  string="[$(date "+%b %d %T")] DWM: "
  if [[ -n "$@" ]]; then
    echo "$string$@" >> $logfile
  else
    read X && echo "$string$X" >> $logfile
  fi
}

[[ -f $HOME/.autostart.zsh ]] && \
  dwmlog "Running autostart: $HOME/.autostart.zsh" \
  source $HOME/.autostart 

[[ -f $HOME/.config/dwm/autostart.zsh ]] && \
  dwmlog "Running autostart: $HOME/.config/dwm/autostart.zsh" \
  source $HOME/.config/dwm/autostart.zsh

dwmlog "Starting DWM"
while true; do
  # Temp fix
  dwm 2>> $logfile >> $logfile
  #dwm 2>&1 | log
  rm /tmp/dwm.sock
  killall -q polybar
  dmwlog "Restarting DWM..."
done
